export type JsonSchema = Record<string, unknown>;
export type HttpMethod = "GET" | "POST" | "DELETE";

export interface OperationParameter {
  name: string;
  description: string;
  schema: JsonSchema;
  required?: boolean;
  sensitive?: boolean;
  cli?: { kind: "argument" | "option"; name: string };
  http?: { in: "path" | "query" | "header" | "body"; name?: string };
  /** Restrict this parameter to one action of a multi-stage operation. */
  actions?: readonly string[];
}

export interface OperationHttpProjection {
  method: HttpMethod;
  path: string;
  action?: string;
  successStatus?: number;
  responseMediaType?: "application/json" | "text/html";
}

export interface OperationDefinition {
  id: string;
  summary: string;
  /** Longer transport-neutral explanation shown by generated API documentation. */
  description?: string;
  mutation: boolean;
  longRunning: boolean;
  capabilities: readonly ("read" | "plan" | "mutate" | "credentials")[];
  parameters: readonly OperationParameter[];
  resultSchema: JsonSchema;
  cli?: { path: readonly string[] };
  http?: readonly OperationHttpProjection[];
  adapterSpecific?: "cli" | "http";
}

const stringSchema = { type: "string" } satisfies JsonSchema;
const booleanSchema = { type: "boolean" } satisfies JsonSchema;
const objectSchema = { type: "object", additionalProperties: true } satisfies JsonSchema;
const snapshotDigestSchema = {
  type: "string",
  pattern: "^[a-f0-9]{64}$",
  description: "SHA-256 digest returned when the immutable process-input snapshot was created",
  examples: ["0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"],
} satisfies JsonSchema;
const processInputSchema = {
  type: "object",
  required: ["schemaVersion", "clientRevision", "payload"],
  properties: {
    schemaVersion: {
      type: "string",
      description: "Version of the form/process data contract understood by the installed generator",
      examples: ["1"],
    },
    clientRevision: {
      type: "string",
      description: "Revision of the UI or process definition that produced this input",
      examples: ["campus-form@42"],
    },
    payload: {
      description: "Pure JSON form data; never executable JavaScript",
      examples: [{ campus: "Mainz", withKidsGroup: true }],
    },
  },
  additionalProperties: false,
} satisfies JsonSchema;
const projectParameters: readonly OperationParameter[] = [
  {
    name: "workspaceId",
    description: "Configured workspace identifier",
    schema: stringSchema,
    required: true,
    http: { in: "path" },
  },
  {
    name: "environment",
    description: "Named environment profile",
    schema: stringSchema,
    cli: { kind: "option", name: "--env" },
    http: { in: "body" },
  },
  {
    name: "configPath",
    description: "Config path within the workspace",
    schema: stringSchema,
    cli: { kind: "option", name: "--config" },
    http: { in: "body" },
  },
  {
    name: "statePath",
    description: "State path within the workspace",
    schema: stringSchema,
    cli: { kind: "option", name: "--state" },
    http: { in: "body" },
  },
];
const workspaceParameter = projectParameters[0]!;
const environmentParameter = projectParameters[1]!;
const configParameter = projectParameters[2]!;
const stateParameter = projectParameters[3]!;

const operationResultSchema = {
  type: "object",
  required: ["operation"],
  properties: { operation: stringSchema },
  additionalProperties: true,
} satisfies JsonSchema;

/**
 * The product surface. Commander, HTTP routing, capability discovery and OpenAPI all enumerate
 * this exact array; an operation is never registered independently in an adapter.
 */
export const operationCatalog: readonly OperationDefinition[] = [
  {
    id: "system.health",
    summary: "Report server health and version",
    mutation: false,
    longRunning: false,
    capabilities: [],
    parameters: [],
    resultSchema: objectSchema,
    http: [{ method: "GET", path: "/api/v1/health" }],
    adapterSpecific: "http",
  },
  {
    id: "system.capabilities",
    summary: "Discover operations and transport capabilities",
    mutation: false,
    longRunning: false,
    capabilities: [],
    parameters: [],
    resultSchema: objectSchema,
    http: [{ method: "GET", path: "/api/v1/capabilities" }],
    adapterSpecific: "http",
  },
  {
    id: "system.openapi",
    summary: "Publish the generated OpenAPI contract",
    mutation: false,
    longRunning: false,
    capabilities: [],
    parameters: [],
    resultSchema: objectSchema,
    http: [{ method: "GET", path: "/api/v1/openapi.json" }],
    adapterSpecific: "http",
  },
  {
    id: "system.docs",
    summary: "Browse the generated OpenAPI contract with Scalar",
    mutation: false,
    longRunning: false,
    capabilities: [],
    parameters: [],
    resultSchema: { type: "string" },
    http: [{ method: "GET", path: "/api/docs", responseMediaType: "text/html" }],
    adapterSpecific: "http",
  },
  {
    id: "session.pair",
    summary: "Exchange a short-lived pairing code for a scoped session",
    mutation: true,
    longRunning: false,
    capabilities: [],
    parameters: [
      {
        name: "code",
        description: "Short-lived pairing code",
        schema: stringSchema,
        required: true,
        sensitive: true,
        http: { in: "body" },
      },
      {
        name: "capabilities",
        description: "Requested session capabilities",
        schema: { type: "array", items: { type: "string", enum: ["read", "plan", "mutate", "credentials"] } },
        http: { in: "body" },
      },
    ],
    resultSchema: objectSchema,
    http: [{ method: "POST", path: "/api/v1/pair" }],
    adapterSpecific: "http",
  },
  {
    id: "workspace.list",
    summary: "List configured workspace roots",
    mutation: false,
    longRunning: false,
    capabilities: ["read"],
    parameters: [],
    resultSchema: objectSchema,
    http: [{ method: "GET", path: "/api/v1/workspaces" }],
    adapterSpecific: "http",
  },
  {
    id: "run.get",
    summary: "Poll progress and terminal result for a long-running operation",
    mutation: false,
    longRunning: false,
    capabilities: ["read"],
    parameters: [
      {
        name: "runId",
        description: "Operation run identifier",
        schema: stringSchema,
        required: true,
        http: { in: "path" },
      },
    ],
    resultSchema: objectSchema,
    http: [{ method: "GET", path: "/api/v1/runs/:runId" }],
    adapterSpecific: "http",
  },
  {
    id: "run.events",
    summary: "Read operation progress as Server-Sent Events",
    mutation: false,
    longRunning: false,
    capabilities: ["read"],
    parameters: [
      {
        name: "runId",
        description: "Operation run identifier",
        schema: stringSchema,
        required: true,
        http: { in: "path" },
      },
    ],
    resultSchema: objectSchema,
    http: [{ method: "GET", path: "/api/v1/runs/:runId/events" }],
    adapterSpecific: "http",
  },
  {
    id: "run.cancel",
    summary: "Request cooperative cancellation of a long-running operation",
    mutation: true,
    longRunning: false,
    capabilities: ["mutate"],
    parameters: [
      {
        name: "runId",
        description: "Operation run identifier",
        schema: stringSchema,
        required: true,
        http: { in: "path" },
      },
    ],
    resultSchema: objectSchema,
    http: [{ method: "DELETE", path: "/api/v1/runs/:runId" }],
    adapterSpecific: "http",
  },
  {
    id: "workspace.init",
    summary: "Initialize a workspace below a configured root",
    mutation: true,
    longRunning: false,
    capabilities: ["mutate"],
    parameters: [
      {
        name: "rootId",
        description: "Configured root in which to initialize",
        schema: stringSchema,
        http: { in: "body" },
      },
      {
        name: "directory",
        description: "Target directory",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "directory" },
        http: { in: "body" },
      },
      {
        name: "template",
        description: "standard or process",
        schema: { type: "string", enum: ["standard", "process"] },
        cli: { kind: "option", name: "--template" },
        http: { in: "body" },
      },
      {
        name: "host",
        description: "ChurchTools base URL",
        schema: stringSchema,
        cli: { kind: "option", name: "--host" },
        http: { in: "body" },
      },
      {
        name: "environment",
        description: "First environment name",
        schema: stringSchema,
        cli: { kind: "option", name: "--env" },
        http: { in: "body" },
      },
      {
        name: "protected",
        description: "Protect the environment",
        schema: booleanSchema,
        cli: { kind: "option", name: "--protected" },
        http: { in: "body" },
      },
      {
        name: "git",
        description: "Initialize Git",
        schema: booleanSchema,
        cli: { kind: "option", name: "--git" },
        http: { in: "body" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["init"] },
    http: [{ method: "POST", path: "/api/v1/workspaces" }],
  },
  {
    id: "environment.list",
    summary: "List non-secret environment profiles",
    mutation: false,
    longRunning: false,
    capabilities: ["read"],
    parameters: [workspaceParameter],
    resultSchema: operationResultSchema,
    cli: { path: ["environment", "list"] },
    http: [{ method: "GET", path: "/api/v1/workspaces/:workspaceId/environments" }],
  },
  {
    id: "auth.status",
    summary: "Read non-secret authentication status",
    mutation: false,
    longRunning: false,
    capabilities: ["read"],
    parameters: [
      workspaceParameter,
      environmentParameter,
      {
        name: "all",
        description: "Check every configured environment",
        schema: booleanSchema,
        cli: { kind: "option", name: "--all" },
        http: { in: "body" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["auth", "status"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/auth/status" }],
  },
  {
    id: "auth.login",
    summary: "Authenticate and store a host-bound token",
    mutation: true,
    longRunning: true,
    capabilities: ["credentials"],
    parameters: [
      workspaceParameter,
      {
        name: "host",
        description: "ChurchTools base URL",
        schema: stringSchema,
        required: true,
        http: { in: "body" },
        cli: { kind: "option", name: "--host" },
      },
      {
        name: "token",
        description: "Personal login token",
        schema: stringSchema,
        sensitive: true,
        http: { in: "body" },
        cli: { kind: "option", name: "--token" },
      },
      {
        name: "username",
        description: "Username or email",
        schema: stringSchema,
        sensitive: true,
        http: { in: "body" },
      },
      {
        name: "password",
        description: "One-shot password",
        schema: stringSchema,
        sensitive: true,
        http: { in: "body" },
      },
      {
        name: "totp",
        description: "Six-digit 2FA continuation code",
        schema: stringSchema,
        sensitive: true,
        http: { in: "body" },
      },
      {
        name: "continuationId",
        description: "Opaque server-held 2FA continuation",
        schema: stringSchema,
        sensitive: true,
        http: { in: "body" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["auth", "login"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/auth/login" }],
  },
  {
    id: "auth.logout",
    summary: "Remove host-bound credentials",
    mutation: true,
    longRunning: false,
    capabilities: ["credentials"],
    parameters: [workspaceParameter, environmentParameter],
    resultSchema: operationResultSchema,
    cli: { path: ["auth", "logout"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/auth/logout" }],
  },
  {
    id: "input.validate",
    summary: "Validate versioned process input",
    description:
      "Checks form/process JSON before it is stored. This feature is optional: users who maintain ct.config.ts directly do not need process-input snapshots.",
    mutation: false,
    longRunning: false,
    capabilities: ["read"],
    parameters: [
      workspaceParameter,
      {
        name: "document",
        description: "Versioned JSON form/process data to validate",
        schema: processInputSchema,
        required: true,
        http: { in: "body" },
        cli: { kind: "argument", name: "file" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["input", "validate"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/input/validate" }],
  },
  {
    id: "input.snapshot",
    summary: "Create an immutable process input snapshot",
    description:
      "Stores one exact version of browser form data and returns its SHA-256 digest. The digest lets plan and apply select the same unmodified input later.",
    mutation: true,
    longRunning: false,
    capabilities: ["mutate"],
    parameters: [
      workspaceParameter,
      {
        name: "document",
        description: "Versioned JSON form/process data to store immutably",
        schema: processInputSchema,
        required: true,
        http: { in: "body" },
        cli: { kind: "argument", name: "file" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["input", "snapshot"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/input/snapshots", successStatus: 201 }],
  },
  {
    id: "input.list",
    summary: "List immutable process input snapshots",
    mutation: false,
    longRunning: false,
    capabilities: ["read"],
    parameters: [workspaceParameter],
    resultSchema: operationResultSchema,
    cli: { path: ["input", "list"] },
    http: [{ method: "GET", path: "/api/v1/workspaces/:workspaceId/input/snapshots" }],
  },
  {
    id: "input.get",
    summary: "Retrieve an immutable process input snapshot",
    mutation: false,
    longRunning: false,
    capabilities: ["read"],
    parameters: [
      workspaceParameter,
      {
        name: "digest",
        description: "Snapshot SHA-256 digest",
        schema: snapshotDigestSchema,
        required: true,
        cli: { kind: "argument", name: "digest" },
        http: { in: "path" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["input", "get"] },
    http: [{ method: "GET", path: "/api/v1/workspaces/:workspaceId/input/snapshots/:digest" }],
  },
  {
    id: "plan",
    summary: "Create a read-only desired-versus-actual plan",
    description:
      "Normally plan reads ct.config.ts. Supplying snapshotDigest instead selects immutable browser form data, which the trusted generator configured by the server operator translates into the normal desired ct model before the same planning logic runs.",
    mutation: false,
    longRunning: true,
    capabilities: ["plan"],
    parameters: [
      ...projectParameters,
      {
        name: "snapshotDigest",
        description:
          "Optional immutable form-input version. Omit it for the normal ct.config.ts workflow. When supplied, the server's trusted generator converts that exact snapshot into the desired ct model.",
        schema: snapshotDigestSchema,
        http: { in: "body" },
        cli: { kind: "option", name: "--input-snapshot" },
      },
      {
        name: "generatorPath",
        description:
          "CLI-only path to a trusted local generator; required together with --input-snapshot. REST clients cannot choose executable code: the server operator configures the generator when starting ct server.",
        schema: stringSchema,
        cli: { kind: "option", name: "--generator" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["plan"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/plans" }],
  },
  {
    id: "apply",
    summary: "Prepare and explicitly execute an apply",
    description:
      "Normally apply reads ct.config.ts. An optional snapshotDigest binds preparation to one exact version of browser form data and its generated desired model, preventing the form input from changing unnoticed between review and execution.",
    mutation: true,
    longRunning: true,
    capabilities: ["plan", "mutate"],
    parameters: [
      ...projectParameters,
      {
        name: "snapshotDigest",
        description:
          "Optional immutable form-input version. Omit it for the normal ct.config.ts workflow. The prepared apply remains bound to this exact digest through execution.",
        schema: snapshotDigestSchema,
        http: { in: "body" },
        cli: { kind: "option", name: "--input-snapshot" },
        actions: ["prepare"],
      },
      {
        name: "generatorPath",
        description:
          "CLI-only path to a trusted local generator; required together with --input-snapshot. REST clients use the generator fixed by the server operator.",
        schema: stringSchema,
        cli: { kind: "option", name: "--generator" },
      },
      {
        name: "backupDir",
        description: "Pre-apply backup directory",
        schema: stringSchema,
        cli: { kind: "option", name: "--backup-dir" },
        http: { in: "body" },
        actions: ["prepare"],
      },
      {
        name: "refresh",
        description: "Refresh changed dynamic groups after apply",
        schema: booleanSchema,
        cli: { kind: "option", name: "--refresh" },
        http: { in: "body" },
        actions: ["prepare"],
      },
      {
        name: "confirmation",
        description: "Core-required confirmation proof",
        schema: objectSchema,
        http: { in: "body" },
        actions: ["execute"],
      },
      {
        name: "idempotencyKey",
        description: "Retry-safe request identity",
        schema: stringSchema,
        http: { in: "header", name: "Idempotency-Key" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["apply"] },
    http: [
      {
        method: "POST",
        path: "/api/v1/workspaces/:workspaceId/applies",
        action: "prepare",
        successStatus: 201,
      },
      {
        method: "POST",
        path: "/api/v1/workspaces/:workspaceId/applies/:operationId/execute",
        action: "execute",
      },
    ],
  },
  {
    id: "coverage",
    summary: "Report managed and unmanaged host coverage",
    mutation: false,
    longRunning: true,
    capabilities: ["read"],
    parameters: [
      workspaceParameter,
      environmentParameter,
      stateParameter,
      {
        name: "type",
        description: "Group type filter",
        schema: stringSchema,
        cli: { kind: "option", name: "--type" },
        http: { in: "body" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["coverage"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/coverage" }],
  },
  {
    id: "refresh",
    summary: "Refresh managed dynamic groups",
    mutation: true,
    longRunning: true,
    capabilities: ["mutate"],
    parameters: [
      workspaceParameter,
      environmentParameter,
      stateParameter,
      {
        name: "group",
        description: "Managed group key",
        schema: stringSchema,
        cli: { kind: "option", name: "--group" },
        http: { in: "body" },
      },
      {
        name: "all",
        description: "Refresh all managed dynamic groups",
        schema: booleanSchema,
        cli: { kind: "option", name: "--all" },
        http: { in: "body" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["refresh"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/refreshes" }],
  },
  {
    id: "adopt.resource",
    summary: "Put one existing ChurchTools resource under management",
    mutation: true,
    longRunning: true,
    capabilities: ["mutate"],
    parameters: [
      workspaceParameter,
      environmentParameter,
      stateParameter,
      {
        name: "type",
        description: "Resource type",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "type" },
        http: { in: "body" },
      },
      {
        name: "id",
        description: "ChurchTools resource id",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "id" },
        http: { in: "body" },
      },
      {
        name: "key",
        description: "Logical key",
        schema: stringSchema,
        cli: { kind: "option", name: "--key" },
        http: { in: "body" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["adopt"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/adoptions/resources" }],
  },
  {
    id: "adopt.groups",
    summary: "Adopt one or more groups",
    mutation: true,
    longRunning: true,
    capabilities: ["mutate"],
    parameters: [
      workspaceParameter,
      environmentParameter,
      stateParameter,
      {
        name: "ids",
        description: "ChurchTools group ids",
        schema: { type: "array", items: stringSchema },
        cli: { kind: "argument", name: "ids" },
        http: { in: "body" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["adopt", "group"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/adoptions/groups" }],
  },
  {
    id: "adopt.grants",
    summary: "Project live grants into portable configuration blocks",
    mutation: false,
    longRunning: true,
    capabilities: ["read"],
    parameters: [
      workspaceParameter,
      environmentParameter,
      stateParameter,
      {
        name: "domainType",
        description: "Permission domain type",
        schema: stringSchema,
        cli: { kind: "argument", name: "domainType" },
        http: { in: "body" },
      },
      {
        name: "domainId",
        description: "Permission domain id",
        schema: stringSchema,
        cli: { kind: "argument", name: "domainId" },
        http: { in: "body" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["adopt", "grants"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/adoptions/grants" }],
  },
  {
    id: "use.resource",
    summary: "Bind an existing ChurchTools resource as a read-only external prerequisite",
    mutation: true,
    longRunning: true,
    capabilities: ["read", "mutate"],
    parameters: [
      workspaceParameter,
      environmentParameter,
      stateParameter,
      {
        name: "type",
        description: "Resource type",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "type" },
        http: { in: "body" },
      },
      {
        name: "id",
        description: "Exact ChurchTools resource id; the CLI also accepts an interactive name search",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "selector" },
        http: { in: "body" },
      },
      {
        name: "key",
        description: "Portable logical key",
        schema: stringSchema,
        required: true,
        cli: { kind: "option", name: "--key" },
        http: { in: "body" },
      },
      {
        name: "owner",
        description: "Optional owner-project coordination hint",
        schema: stringSchema,
        cli: { kind: "option", name: "--owner" },
        http: { in: "body" },
      },
      {
        name: "acceptChanges",
        description: "Explicitly accept a changed identity or replacement",
        schema: booleanSchema,
        cli: { kind: "option", name: "--yes" },
        http: { in: "body" },
      },
      {
        name: "dryRun",
        description: "Validate without changing state",
        schema: booleanSchema,
        cli: { kind: "option", name: "--dry-run" },
        http: { in: "body" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["use"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/external-bindings" }],
  },
  {
    id: "release.managed",
    summary: "Stop managing a resource without changing it in ChurchTools",
    mutation: true,
    longRunning: false,
    capabilities: ["mutate"],
    parameters: [
      ...projectParameters,
      {
        name: "type",
        description: "Resource type",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "type" },
        http: { in: "path" },
        actions: ["prepare"],
      },
      {
        name: "key",
        description: "Logical key to release",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "key" },
        http: { in: "path" },
        actions: ["prepare"],
      },
      {
        name: "force",
        description: "Allow release while the key remains declared or referenced",
        schema: booleanSchema,
        cli: { kind: "option", name: "--force" },
        http: { in: "body" },
        actions: ["prepare"],
      },
      {
        name: "dryRun",
        description: "Preview without changing state",
        schema: booleanSchema,
        cli: { kind: "option", name: "--dry-run" },
      },
      {
        name: "confirmation",
        description: "Core-required environment or logical-key confirmation proof",
        schema: objectSchema,
        http: { in: "body" },
        actions: ["execute"],
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["unadopt"] },
    http: [
      {
        method: "POST",
        path: "/api/v1/workspaces/:workspaceId/releases/managed/execute/:operationId",
        action: "execute",
      },
      {
        method: "POST",
        path: "/api/v1/workspaces/:workspaceId/releases/managed/prepare/:type/:key",
        action: "prepare",
        successStatus: 201,
      },
    ],
  },
  {
    id: "release.external",
    summary: "Remove an external binding without changing ChurchTools",
    mutation: true,
    longRunning: false,
    capabilities: ["mutate"],
    parameters: [
      ...projectParameters,
      {
        name: "type",
        description: "Resource type",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "type" },
        http: { in: "path" },
        actions: ["prepare"],
      },
      {
        name: "key",
        description: "Logical key to release",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "key" },
        http: { in: "path" },
        actions: ["prepare"],
      },
      {
        name: "force",
        description: "Allow release while the key remains declared or referenced",
        schema: booleanSchema,
        cli: { kind: "option", name: "--force" },
        http: { in: "body" },
        actions: ["prepare"],
      },
      {
        name: "dryRun",
        description: "Preview without changing state",
        schema: booleanSchema,
        cli: { kind: "option", name: "--dry-run" },
      },
      {
        name: "confirmation",
        description: "Core-required environment or logical-key confirmation proof",
        schema: objectSchema,
        http: { in: "body" },
        actions: ["execute"],
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["unuse"] },
    http: [
      {
        method: "POST",
        path: "/api/v1/workspaces/:workspaceId/releases/external/execute/:operationId",
        action: "execute",
      },
      {
        method: "POST",
        path: "/api/v1/workspaces/:workspaceId/releases/external/prepare/:type/:key",
        action: "prepare",
        successStatus: 201,
      },
    ],
  },
  {
    id: "ownership.check",
    summary: "Check managed and external ownership claims within a workspace tree",
    mutation: false,
    longRunning: true,
    capabilities: ["read"],
    parameters: [
      workspaceParameter,
      {
        name: "root",
        description: "Complete coordination-scope directory within the workspace",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "root" },
        http: { in: "body" },
      },
      {
        name: "environment",
        description: "Environment name to inspect in every discovered project",
        schema: stringSchema,
        required: true,
        cli: { kind: "option", name: "--env" },
        http: { in: "body" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["ownership", "check"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/ownership/check" }],
  },
  {
    id: "state.list",
    summary: "List managed state entries",
    mutation: false,
    longRunning: false,
    capabilities: ["read"],
    parameters: [workspaceParameter, environmentParameter, stateParameter],
    resultSchema: operationResultSchema,
    cli: { path: ["state", "list"] },
    http: [{ method: "POST", path: "/api/v1/workspaces/:workspaceId/state/list" }],
  },
  {
    id: "state.remove",
    summary: "Remove one managed state entry without touching ChurchTools",
    mutation: true,
    longRunning: false,
    capabilities: ["mutate"],
    parameters: [
      workspaceParameter,
      environmentParameter,
      configParameter,
      stateParameter,
      {
        name: "type",
        description: "Resource type",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "type" },
        http: { in: "path" },
      },
      {
        name: "key",
        description: "Logical resource key",
        schema: stringSchema,
        required: true,
        cli: { kind: "argument", name: "key" },
        http: { in: "path" },
      },
      {
        name: "force",
        description: "Remove even while declared",
        schema: booleanSchema,
        cli: { kind: "option", name: "--force" },
        http: { in: "body" },
      },
      {
        name: "dryRun",
        description: "Preview without writing",
        schema: booleanSchema,
        cli: { kind: "option", name: "--dry-run" },
        http: { in: "body" },
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["state", "rm"] },
    http: [{ method: "DELETE", path: "/api/v1/workspaces/:workspaceId/state/:type/:key" }],
  },
  {
    id: "destroy",
    summary: "Prepare and explicitly execute resource destruction",
    mutation: true,
    longRunning: true,
    capabilities: ["plan", "mutate"],
    parameters: [
      workspaceParameter,
      environmentParameter,
      stateParameter,
      {
        name: "targets",
        description: "Logical keys",
        schema: { type: "array", items: stringSchema },
        required: true,
        cli: { kind: "option", name: "--target" },
        http: { in: "body" },
        actions: ["prepare"],
      },
      {
        name: "memberFields",
        description: "Portable group member-field identities",
        schema: { type: "array", items: stringSchema },
        cli: { kind: "option", name: "--member-field" },
        http: { in: "body" },
        actions: ["prepare"],
      },
      {
        name: "backupDir",
        description: "Pre-destroy backup directory",
        schema: stringSchema,
        cli: { kind: "option", name: "--backup-dir" },
        http: { in: "body" },
        actions: ["prepare"],
      },
      {
        name: "confirmation",
        description: "Core-required confirmation proof",
        schema: objectSchema,
        http: { in: "body" },
        actions: ["execute"],
      },
    ],
    resultSchema: operationResultSchema,
    cli: { path: ["destroy"] },
    http: [
      {
        method: "POST",
        path: "/api/v1/workspaces/:workspaceId/destroys",
        action: "prepare",
        successStatus: 201,
      },
      {
        method: "POST",
        path: "/api/v1/workspaces/:workspaceId/destroys/:operationId/execute",
        action: "execute",
      },
    ],
  },
  {
    id: "read.raw",
    summary: "Read allowlisted or explicit ChurchTools API resources",
    mutation: false,
    longRunning: true,
    capabilities: ["read"],
    parameters: [],
    resultSchema: objectSchema,
    cli: { path: ["get"] },
    adapterSpecific: "cli",
  },
  {
    id: "permission.catalog",
    summary: "Inspect or refresh the permission catalog",
    mutation: true,
    longRunning: true,
    capabilities: ["read", "mutate"],
    parameters: [],
    resultSchema: objectSchema,
    cli: { path: ["permissions"] },
    adapterSpecific: "cli",
  },
  {
    id: "permission.report",
    summary: "Generate permission reports",
    mutation: false,
    longRunning: true,
    capabilities: ["read"],
    parameters: [],
    resultSchema: objectSchema,
    cli: { path: ["report"] },
    adapterSpecific: "cli",
  },
  {
    id: "shell.completion",
    summary: "Generate shell completion hooks",
    mutation: false,
    longRunning: false,
    capabilities: [],
    parameters: [],
    resultSchema: objectSchema,
    cli: { path: ["completion"] },
    adapterSpecific: "cli",
  },
  {
    id: "server.start",
    summary: "Start the versioned REST API adapter",
    mutation: false,
    longRunning: true,
    capabilities: [],
    parameters: [],
    resultSchema: objectSchema,
    cli: { path: ["server"] },
    adapterSpecific: "cli",
  },
] as const;

export function operationById(id: string): OperationDefinition {
  const definition = operationCatalog.find((candidate) => candidate.id === id);
  if (!definition) throw new Error(`Unknown operation ${id}.`);
  return definition;
}

export function cliRootNames(catalog: readonly OperationDefinition[] = operationCatalog): string[] {
  return [...new Set(catalog.flatMap((definition) => (definition.cli ? [definition.cli.path[0]!] : [])))];
}
